# Generated by Django 5.1.5 on 2025-02-10 12:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0002_cabin_detailed_description_cabin_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabin",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="cabin",
            name="image_alt",
            field=models.CharField(max_length=100),
        ),
    ]
