# Generated by Django 5.1.5 on 2025-02-10 13:04

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0003_alter_cabin_image_alter_cabin_image_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabin",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=80,
                scale=None,
                size=[600, None],
                upload_to="cabins/",
            ),
        ),
    ]
