# Generated by Django 5.1.5 on 2025-02-10 14:24

import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0004_alter_cabin_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabin",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=80,
                scale=None,
                size=[600, None],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="cabins/",
            ),
        ),
    ]
