# Generated by Django 5.1.5 on 2025-02-11 13:58

import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0005_alter_cabin_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabin",
            name="bathroom_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=80,
                scale=None,
                size=[350, 200],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="cabins/bathroom/",
            ),
        ),
        migrations.AddField(
            model_name="cabin",
            name="bedroom_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=80,
                scale=None,
                size=[350, 200],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="cabins/bedroom/",
            ),
        ),
        migrations.AddField(
            model_name="cabin",
            name="kitchen_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=80,
                scale=None,
                size=[350, 200],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="cabins/kitchen/",
            ),
        ),
        migrations.AlterField(
            model_name="cabin",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=80,
                scale=None,
                size=[600, 335],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="cabins/",
            ),
        ),
    ]
