# Generated by Django 5.1.5 on 2025-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0007_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveBigIntegerField(
                choices=[(1, "1★"), (2, "2★"), (3, "3★"), (4, "4★"), (5, "5★")]
            ),
        ),
    ]
